import {
  NUMBER_AUTH_BG_PICS,
  NUMBER_OF_LAST_EVENTS_HOME,
  PATH_AUTH_VIDEO,
  PATH_LOADING_SPINNER,
  PATH_LOGO_PONTHE_SVG,
  PATH_GALERIES_SVG,
  PATH_DASHBOARD_SVG,
  PATH_MEMBERS_SVG,
  PATH_MATOS_SVG,
  PATH_LOGOUT_SVG,
  PATH_NOT_FOUND_IMAGE,
  LOVE_PICS,
} from './constants/Images';
import { LINKS, BUTTON_LINKS_ADMIN } from './constants/ExternalLinks';
import { LANGUAGES, FLAGS_BY_LANG } from './constants/Languages';
import { BREAKPOINTS } from './constants/Breakpoints';


export const EXTENSION_MAILS_ENPC = '@eleves.enpc.fr';
export const AVAILABLE_PROMOTIONS = ['015', '016', '017', '018', '019', '020', '021', '022'];


export {
  NUMBER_AUTH_BG_PICS,
  NUMBER_OF_LAST_EVENTS_HOME,
  PATH_AUTH_VIDEO,
  PATH_LOADING_SPINNER,
  PATH_LOGO_PONTHE_SVG,
  PATH_GALERIES_SVG,
  PATH_DASHBOARD_SVG,
  PATH_MEMBERS_SVG,
  PATH_MATOS_SVG,
  PATH_LOGOUT_SVG,
  PATH_NOT_FOUND_IMAGE,
  LOVE_PICS,
  LINKS,
  BUTTON_LINKS_ADMIN,
  LANGUAGES,
  FLAGS_BY_LANG,
  BREAKPOINTS,
};
